name: DS3 Java CLI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-deps:
    name: Compile main and test classes with fresh dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          check-latest: true
      - run: ./gradlew clean classes testClasses --refresh-dependencies
  test:
    name: Test with multiple Temurin JDK versions
    strategy:
      matrix:
        test-jdk-version: [ 8, 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Setup Temurin JDK ${{ matrix.test-jdk-version }}
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.test-jdk-version }}
          cache: 'gradle'
          check-latest: true
      - name: Compile and assemble main project with Temurin JDK ${{ matrix.test-jdk-version }}
        run: ./gradlew clean assemble
      - name: Test with Temurin JDK ${{ matrix.test-jdk-version }}
        run: ./gradlew -S clean :ds3_java_cli:test --info
